/*
2022년 1월의 도서 판매 데이터를 기준으로 
저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
저자 ID(AUTHOR_ID), 
저자명(AUTHOR_NAME), 
카테고리(CATEGORY), 
매출액(SALES) 리스트를 출력하는 SQL문을 작성해주세요.

<정렬>
결과는 저자 ID를 오름차순
저자 ID가 같다면 카테고리를 내림차순
*/
WITH JANUARY_BOOK_SALES AS (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
),BOOK_SALES AS (
    SELECT a.BOOK_ID, a.CATEGORY, a.AUTHOR_ID, a.PRICE * b.SALES AS TOTAL_SALES
    FROM BOOK a
    JOIN JANUARY_BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
)

SELECT a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, SUM(a.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK_SALES a
JOIN AUTHOR b ON a.AUTHOR_ID = b.AUTHOR_ID
GROUP BY b.AUTHOR_NAME, a.CATEGORY
ORDER BY a.AUTHOR_ID ASC, a.CATEGORY DESC