-- ITEM_ID가 PARENT_ITEM_ID에 없을 때 
with NOT_UPGRADE_ITEM AS (
    SELECT ITEM_ID, PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NOT NULL
    )
)
SELECT a.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO a
JOIN NOT_UPGRADE_ITEM b on a.ITEM_ID = b.ITEM_ID
ORDER BY a.ITEM_ID DESC


