/*
USER_INFO 테이블과 ONLINE_SALE 테이블에서 
2021년에 가입한 전체 회원들 중 
상품을 구매한 회원 수와 
상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)을 
년, 월 별로 출력하는 SQL문을 작성

상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림

<정렬>
전체 결과는 년을 기준으로 오름차순 정렬
년이 같다면 월을 기준으로 오름차순 정렬해주세요.
*/
WITH WHETHER_SALES AS (
    SELECT a.USER_ID, DATE_FORMAT(b.SALES_DATE, "%Y") AS YEAR, MONTH(b.SALES_DATE) AS MONTH
    FROM USER_INFO a
    JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
    WHERE DATE_FORMAT(JOINED, "%Y") = '2021'
),BUYED_USER AS (
    SELECT YEAR, MONTH, COUNT(DISTINCT USER_ID) AS TOTAL_USER
    FROM WHETHER_SALES
    GROUP BY YEAR, MONTH
)
SELECT YEAR, MONTH, TOTAL_USER AS PURCHASED_USERS, ROUND(TOTAL_USER / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM BUYED_USER
ORDER BY YEAR, MONTH