/*
자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 
대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성

대여 금액을 기준으로 내림차순 정렬하고, 
대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬
*/
WITH TRUCK_USING_FEE AS (
    SELECT 
        a.HISTORY_ID, 
        b.CAR_TYPE, 
        TIMESTAMPDIFF(DAY, a.START_DATE, a.END_DATE) + 1 AS USING_DAY, 
        b.DAILY_FEE * (TIMESTAMPDIFF(DAY, a.START_DATE, a.END_DATE) + 1) AS USING_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
    JOIN CAR_RENTAL_COMPANY_CAR b 
    ON a.CAR_ID = b.CAR_ID
    WHERE b.CAR_TYPE = '트럭'
),
TRUCK_DISCOUNT AS (
    SELECT 
        CONVERT(SUBSTRING_INDEX(DURATION_TYPE, '일', 1), SIGNED) AS DURATION, 
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT 
    t.HISTORY_ID,
    CASE 
        WHEN t.USING_DAY >= 90 THEN ROUND(t.USING_FEE * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT WHERE DURATION = 90)) / 100 , 0)
        WHEN t.USING_DAY >= 30 THEN ROUND(t.USING_FEE * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT WHERE DURATION = 30)) / 100, 0)
        WHEN t.USING_DAY >= 7 THEN ROUND(t.USING_FEE * (100 - (SELECT DISCOUNT_RATE FROM TRUCK_DISCOUNT WHERE DURATION = 7)) / 100, 0)
        ELSE t.USING_FEE
    END AS FEE
FROM TRUCK_USING_FEE t
ORDER BY FEE DESC, HISTORY_ID DESC;
