WITH RECURSIVE TEMP AS (
    SELECT 0 AS HOUR
    UNION
    SELECT HOUR + 1
    FROM TEMP
    WHERE HOUR < 23
)



SELECT a.HOUR, COUNT(b.ANIMAL_ID) AS COUNT
FROM TEMP a
LEFT JOIN ANIMAL_OUTS b ON a.HOUR = HOUR(b.DATETIME)
GROUP BY HOUR
ORDER BY HOUR