/*
- 프론트엔드 기술을 가지고 있지 않는다면 비트 연산이 0이 나옴
*/

WITH FRONT_STACK AS (
    SELECT SUM(CODE) AS TOTAL_CODE
    FROM SKILLCODES
    GROUP BY CATEGORY
    HAVING CATEGORY = 'Front End'
)

SELECT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS a
JOIN FRONT_STACK b ON a.SKILL_CODE & b.TOTAL_CODE > 0
ORDER BY a.ID