/*
<요구조건>
테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

<출력>
회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력

<정렬>
리뷰 작성일을 기준으로 오름차순, 
리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순 정렬
*/
WITH MOST_REVIEWER AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_TOTAL
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING REVIEW_TOTAL = (
        SELECT COUNT(MEMBER_ID) AS REVIEW_TOTAL
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY REVIEW_TOTAL DESC
        LIMIT 1
    )
), MOST_REVIEWER_TEXT AS (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM MOST_REVIEWER)
)

SELECT a.MEMBER_NAME, b.REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE a
JOIN MOST_REVIEWER_TEXT b ON a.MEMBER_ID = b.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC


