WITH MAX_LENGTH_TABLE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH 
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT a.ID AS ID, b.FISH_NAME AS FISH_NAME, c.MAX_LENGTH AS LENGTH
FROM FISH_INFO a
LEFT JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
INNER JOIN MAX_LENGTH_TABLE c ON a.LENGTH = c.MAX_LENGTH AND a.FISH_TYPE = c.FISH_TYPE
ORDER BY a.ID;



