-- PRODUCT_NAME은 집계 함수가 아니기 때문에, SQL은 그룹 내에서 임의의 값을 반환할 가능성이 크다.

SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC;
